### ISSUE TITLE
App crashes on start if we use Firebase on menu controller

### ISSUE THREAD

**Issue by adomanski** [Friend-LGA/LGSideMenuController#155] opened 2018-05-07 06:52 UTC
The initialization of segues inside awakeFromNib causes the breaking the whole application's initialization lifecycle because of the execution of viewDidLoad methods of Base and both Left/Right controllers before execution of application's delegate didFinishLaunchingWithOptions

Steps to reproduce:

1. Integrate Firebase and Firebase Database to the app
2. Add Firebase initialization to didFinishLaunchingWithOptions (according to Firebase documentation)
3. Add accessing to Firebase Realtime Database functionality inside viewDidLoad method of Left or Right menu controller
4. Run

Please look at my pull request for code changes https://github.com/Friend-LGA/LGSideMenuController/pull/154

**Comment by Friend-LGA** [comment] 2021-02-06 12:57
Should be fixed now.
Feel free to reopen if the issue is still actual.

**Closed by Friend-LGA** 2021-02-06 12:57 UTC
