### ISSUE TITLE
View will appear called on orientation change

### ISSUE THREAD

**Issue by rajtharan-g** [Friend-LGA/LGSideMenuController#163] opened 2018-08-07 08:40 UTC
When I change the app from portrait to landscape or vice versa, the view will appear method of the view controller gets called, which I hope shouldn't be the case. Any possible solutions or alternate is height appreciated.

**Comment by sherifnosseir** [comment] 2020-03-11 00:09
This issue is affecting our application as well.

This seems to be a side effect of re-adding controllers as subviews.
Any feedback would be greatly appreciated.

Thanks.

**Comment by Friend-LGA** [comment] 2021-02-06 12:47
Should be fixed now.
Feel free to reopen if the issue is still actual.

**Closed by Friend-LGA** 2021-02-06 12:47 UTC
