### ISSUE TITLE
isRightViewHidesOnTouch is not working

### ISSUE THREAD

**Issue by junestchick** [Friend-LGA/LGSideMenuController#117] opened 2017-08-04 07:36 UTC
Hi, in Appdelegate I set 
sideMenuController?.isRightViewHidesOnTouch = false
but it does not work. Can you help me pls?

**Comment by Friend-LGA** [comment] 2021-04-06 16:31
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-06 16:31 UTC
