### ISSUE TITLE
Showing left view controller shows a black screen

### ISSUE THREAD

**Issue by nastasiupta** [Friend-LGA/LGSideMenuController#124] opened 2017-09-16 11:12 UTC
I use this to create a left menu:

```
        if let viewController = UIViewController.instantiate(type: .menu) as? MenuViewController {
            guard let mainViewController = navigationController?.childViewControllers.first else {
                return
            }
            viewController.view.backgroundColor = UIColor.green
            sideMenuController = LGSideMenuController(rootViewController: mainViewController, leftViewController: viewController, rightViewController: nil)
            sideMenuController?.leftViewWidth = 250.0
            sideMenuController?.leftViewPresentationStyle = .slideAbove
            sideMenuController?.showLeftViewAnimated()
        }
```

The navigation controller is the root view of the UIWindow, and main view controller is the only view controller from the childViewControllers.
The result is a black screen

I also tried to send rootviewcontroller as nil but no effect, a black view is setting under the app main view controller

**Comment by mob-rockstar** [comment] 2019-12-21 12:31
I have faced same issue, it is showing black screen instead left menu VC.
![Simulator Screen Shot - iPhone XR - 2019-12-21 at 15 30 55](https://user-images.githubusercontent.com/16888110/71307947-f1999780-2406-11ea-8e40-995dd1cc694d.png)

**Comment by Friend-LGA** [comment] 2021-04-06 16:34
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-06 16:34 UTC
