### ISSUE TITLE
leftViewAlwaysVisibleOptions on Landscape doesn't work as expected.

### ISSUE THREAD

**Issue by Marcin-Kapusta** [Friend-LGA/LGSideMenuController#107] opened 2017-05-31 08:46 UTC
I expect from the following code that leftView should be always visible on iPad in Landscape. Try minimize application and maximize in landscape and You will see that leftView is becoming black after maximizing. I'm testing this using iPad Pro with iOS 10.2.1 (14D27).

There is nothing special in rootVC and leftVC that could broke this behaviour. I think this is a Bug.

```
let editorMenuController = LGSideMenuController(
            rootViewController: rootVC,
            leftViewController: leftVC,
            rightViewController: nil)
editorMenuController.leftViewWidth = 220.0
editorMenuController.leftViewPresentationStyle = .slideBelow
editorMenuController.leftViewAlwaysVisibleOptions = [.onPadLandscape]
```

**Comment by Marcin-Kapusta** [comment] 2017-06-06 10:43
I also have made tests on Demo Application. It doesn't really matter which demo I run (swift, objc, storyboard based or not) select `Landscape always visible` and then hit home button and return to the app. The pane that should be always visible is disappearing after animation finishes. Does somebody know how to fix this or make quick workaround. I'm working on iPad Pro iOS 10.2.1

**Comment by Marcin-Kapusta** [comment] 2017-06-07 10:12
I posted this question on Stackoverflow. I think this is related to this behaviour: https://stackoverflow.com/questions/44409603/unexpected-orientation-change-on-ipad-pro-ios-10-3-2

**Comment by louros** [comment] 2017-06-28 10:53
This can be kind of patched up by listening to 'UIApplicationDidEnterBackgroundNotification' and stopping layout update in 'viewWillLayoutSubviews' when the app is exiting to background.

**Comment by DarkwingXL** [comment] 2017-08-02 09:57
As I see it the leftViewAlwaysVisibleOptions property is readonly now. Does it mean what you have to set this behaviour with a different way?
The Always visible options - documentation chapter steel not updated and it tell what you can just set it like this:

**Comment by iDevo** [comment] 2018-10-09 13:14
Hey! Thanks for sharing! 

I just want to share my solution too, which is based on @DarkwingXL s solution but I digged down in the code, to get a cleaner one: 

In your side menu ViewController (or any other visible vc) add the following code: 

```
override func viewDidAppear(_ animated: Bool) {
        // Workaround black menu bug
        NotificationCenter.default.addObserver(self, selector: #selector(appEntersForeground), name: NSNotification.Name.UIApplicationWillEnterForeground, object: nil)
}

@objc func appEntersForeground() {
        self.sideMenuController!.view.setNeedsLayout()
        self.sideMenuController?.updateLayoutsAndStyles()
}
```

**Comment by DaniSpringer** [comment] 2020-10-29 03:28
> Hey! Thanks for sharing!
> 
> I just want to share my solution too, which is based on @DarkwingXL s solution but I digged down in the code, to get a cleaner one:
> 
> In your side menu ViewController (or any other visible vc) add the following code:
> 
> ```
> override func viewDidAppear(_ animated: Bool) {
>         // Workaround black menu bug
>         NotificationCenter.default.addObserver(self, selector: #selector(appEntersForeground), name: NSNotification.Name.UIApplicationWillEnterForeground, object: nil)
> }
> 
> @objc func appEntersForeground() {
>         self.sideMenuController!.view.setNeedsLayout()
>         self.sideMenuController?.updateLayoutsAndStyles()
> }
> ```

Why not ```viewDidLoad``` instead? Have you tested this?

**Comment by DaniSpringer** [comment] 2020-10-29 03:29
> I posted this question on Stackoverflow. I think this is related to this behaviour: https://stackoverflow.com/questions/44409603/unexpected-orientation-change-on-ipad-pro-ios-10-3-2

Link gone! What was the Q&A?

**Comment by Friend-LGA** [comment] 2021-04-06 16:27
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-06 16:27 UTC
