### ISSUE TITLE
Status bar layout glitch when using gestures to close side menu

### ISSUE THREAD

**Issue by SticklyMan** [Friend-LGA/LGSideMenuController#156] opened 2018-06-05 19:59 UTC
This is a minor cosmetic issue that I noticed started happening in iOS 11.

I have a left side menu that can be opened via button or by gesture. The status bar is visible on the main controller, but is hidden when the left menu is open.

When the left menu is opened (by button or gesture), the status bar correctly disappears and the main controller leaves a space for the status bar on the navigation header.

When the left menu is closed by button, it will animate closed as expected, with the status bar reappearing. However, when it is closed via gesture, the primary view controller suddenly updates to remove the blank space for the status bar on the navigation header.

My best guess is that the setting of the view's transform on this line is doing some additional layout calculations that it wasn't doing before in iOS 9/10, but I'm not sure where to proceed from here.
https://github.com/Friend-LGA/LGSideMenuController/blob/master/LGSideMenuController/LGSideMenuController.m#L1926

Example: (Sorry for the large images)

Before -> After gesture start
![menu-normal](https://user-images.githubusercontent.com/95759/40999990-cc0b05fc-68c9-11e8-998d-36fe80ad78bf.jpg) ![menu-after-gesture](https://user-images.githubusercontent.com/95759/40999991-cc29afa2-68c9-11e8-82f4-93d387edf507.jpg)

Thanks!

**Comment by Lailan** [comment] 2019-02-27 17:42
@SticklyMan Did you solve this?

**Comment by SticklyMan** [comment] 2019-02-27 17:50
@Lailan Nope, we're still observing this issue.  I have unfortunately not had enough time to dig into a low priority issue like this.

**Comment by Friend-LGA** [comment] 2021-02-06 12:56
Should be fixed now.
Feel free to reopen if the issue is still actual.

**Closed by Friend-LGA** 2021-02-06 12:56 UTC
