### ISSUE TITLE
Status bar is getting white when i manually drag the side menu

### ISSUE THREAD

**Issue by TaimoorSaeed** [Friend-LGA/LGSideMenuController#169] opened 2019-02-28 00:06 UTC
![screenshot 2019-02-28 at 5 03 06 am](https://user-images.githubusercontent.com/4158494/53531937-a67c6400-3b16-11e9-99c2-7a148d694e8a.png)

**Comment by Friend-LGA** [comment] 2021-02-06 12:36
Should be fixed now.
Fell free to reopen if the issue is still actual.

**Closed by Friend-LGA** 2021-02-06 12:36 UTC
