### ISSUE TITLE
when make root UITabBarController and open side menu for on time and do push for some view controller and when make popviewcontroller,  viewWillAppear, viewDidAppear not work for view controllers in UITabBarController 

### ISSUE THREAD

**Issue by salah-mohammed** [Friend-LGA/LGSideMenuController#147] opened 2018-03-04 10:41 UTC

**Comment by Friend-LGA** [comment] 2021-04-06 16:52
The title is a little bit confusing.
Hopefully your issue should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible. And please, add more details.

**Closed by Friend-LGA** 2021-04-06 16:52 UTC
