### ISSUE TITLE
Toggle In-Call Status Bar Problem

### ISSUE THREAD

**Issue by xjimi** [Friend-LGA/LGSideMenuController#118] opened 2017-08-08 15:42 UTC
When i "Toggle In-Call Status Bar" and call "showLeftViewAnimated:"
the problem happened.

![in-call](https://user-images.githubusercontent.com/1509873/29080711-182d36ea-7c93-11e7-8694-6a4faa2a4e71.gif)

**Comment by subhashsanghani** [comment] 2018-10-22 12:17
Yes i have same issue please provide solution...

**Comment by xjimi** [comment] 2018-10-23 02:51
My solution :

- (void)addLGNotification
{

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sideMenuControllerWillShowLeftView) name:LGSideMenuWillShowLeftViewNotification object:nil];

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sideMenuControllerDidDismissLeftView) name:LGSideMenuDidHideLeftViewNotification object:nil];
}

- (void)sideMenuControllerWillShowLeftView {
    if ([UIApplication sharedApplication].statusBarFrame.size.height == 20) {
        [self setStatusBarHidden:YES animation:UIStatusBarAnimationFade];
    }
}

- (void)sideMenuControllerDidDismissLeftView {
    [self setStatusBarHidden:NO animation:UIStatusBarAnimationFade];
}

- (void)setStatusBarHidden:(BOOL)hidden
            statusBarStyle:(UIStatusBarStyle)statusBarStyle
                 animation:(UIStatusBarAnimation)animation
{
    self.statusBarStyle = statusBarStyle;
    self.statusBarHidden = hidden;
    self.statusBarAnimation = animation;

    [UIView animateWithDuration:.3 delay:0 options:UIViewAnimationOptionCurveEaseOut animations:^{
        [self setNeedsStatusBarAppearanceUpdate];
    } completion:^(BOOL finished) {
    }];
}

**Comment by Friend-LGA** [comment] 2021-04-15 08:46
Should be fixed now.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-15 08:46 UTC
