### ISSUE TITLE
disable left view completely?

### ISSUE THREAD

**Issue by NoctizJ** [Friend-LGA/LGSideMenuController#130] opened 2017-10-27 01:04 UTC
Hi, First I wanna say good job making this.
However I didn't find a good doc for this.

I only want right side view. In the setup I set self.leftViewEnabled = NO;
I am using storyboard. It spits exception at 
[self performSegueWithIdentifier:LGSideMenuSegueLeftIdentifier sender:nil];

Do I have to set a segue for left view? How do I disable left view, since I don't need it.

**Comment by iDevelopper** [comment] 2017-10-30 12:01
If you don't want a left view controller don't create it. And delete the exception breakpoint, if you don't want the app to break.

**Comment by danielCarlosCE** [comment] 2018-02-16 18:10
+1

**Comment by danielCarlosCE** [comment] 2018-02-16 18:15
The problem is the code checks the existence this way: 
```
@try {
  [self performSegueWithIdentifier:LGSideMenuSegueLeftIdentifier sender:nil];
}
```

So, if you don't have leftView, it will always throw an exception.

**Comment by danielCarlosCE** [comment] 2018-02-27 02:26
@NoctizJ one way is actually creating a left segue and select the option to disable left menu. that's far from a good solution, but it stops the problem

**Comment by Friend-LGA** [comment] 2021-04-06 16:35
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-06 16:35 UTC
