### ISSUE TITLE
UINavigationController should have parent view controller:(null) but actual parent is xxxxxx

### ISSUE THREAD

**Issue by yangjunfeng22** [Friend-LGA/LGSideMenuController#110] opened 2017-06-21 06:35 UTC
It would crash when set the rootViewController with UINavigationController.

child view controller:<STNavigationController: 0x156041000> should have parent view controller:(null) but actual parent is:<STMainViewController: 0x156102c00>

0 CoreFoundation	___exceptionPreprocess + 124
1 libobjc.A.dylib	objc_exception_throw + 56
2 CoreFoundation	-[NSException initWithCoder:]
3 UIKit	-[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 296
4 UIKit	-[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 244
5 UIKit	-[UIView(Internal) _addSubview:positioned:relativeTo:] + 412
6 UIKit	-[UIView(Hierarchy) addSubview:] + 828
7 UIKit	-[UITransitionView transition:fromView:toView:removeFromView:] + 1472
8 UIKit	-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1632
9 UIKit	___56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 2472
10 UIKit	__runAfterCACommitDeferredBlocks + 292
11 UIKit	__cleanUpAfterCAFlushAndRunDeferredBlocks + 560
12 UIKit	__afterCACommitHandler + 168
13 CoreFoundation	___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
14 CoreFoundation	___CFRunLoopDoObservers + 372
15 CoreFoundation	___CFRunLoopRun + 1024
16 CoreFoundation	CFRunLoopRunSpecific + 444
17 GraphicsServices	GSEventRunModal + 180
18 UIKit	-[UIApplication _run] + 684
19 UIKit	UIApplicationMain + 208

**Comment by luoganzhi** [comment] 2017-11-13 07:59
i meet the same trouble

**Comment by neghao** [comment] 2018-05-10 02:52
i meet the same trouble

**Comment by neghao** [comment] 2018-05-10 02:54
Finally, how did you solve?

**Comment by Gopesh** [comment] 2018-05-28 12:35
Is there any solution around this?

**Comment by fongfonglin** [comment] 2019-01-14 12:01
i meet the same trouble

**Comment by wata-chinhtran** [comment] 2019-01-15 11:39
Crash at line
 objc_setAssociatedObject(rootViewController, @"sideMenuController", self, OBJC_ASSOCIATION_ASSIGN);

**Comment by BilalMustafa** [comment] 2019-05-22 08:46
Any updates on this issue?

**Comment by LUJYM** [comment] 2019-12-03 11:51
anybody solved it?

**Comment by Friend-LGA** [comment] 2021-04-06 16:29
Should be fixed in the new version. Please validate.
Feel free to reopen if the issue is still reproducible.

**Closed by Friend-LGA** 2021-04-06 16:29 UTC
